### PR TITLE
Unbreak build with libinput 1.19.1

### PR DESCRIPTION
**Pull request by Mindavi**
This prevents issues like where libinput added new enum values.
It should not break on that.

We could also add the enum values, but since they're no-opped anyway, I'm not sure if that's valuable. It also makes this less backwards-compatible (but I don't know if I should care about that).

Tested by building with:
- `nix-shell -I nixpkgs=/my/local/nixpkgs -p freetype libinput libdrm pkg-config libxkbcommon ripgrep vim git less --pure`
- `make -j LVGL_ENV_SIMULATOR=0`

### CODE REVIEW

**Comment by samueldr** [comment]
The upstream project uses `-Wswitch-enum`, so whenever this is refactored back into a form that can be contributed back upstream, it is required to be enabled.

So yeah, adding the no-op cases has value. Even though it's really annoying since our dependencies are not strictly locked.

**Comment by Mindavi** [comment]
I changed the PR to remove the no-op -Wno-switch-enum and to add the missing enum cases.

**Comment by Mindavi** [comment]
Any input needed on my side? I did use this change in my cross-compilation adventures: https://github.com/Mindavi/mobile-nixos/commit/f180a3978c3ba2bd6d9272119734fff5ecff9dff without issues. I'm not sure how to _properly_ test it though.

Would like to get this in to unbreak mobile-nixos hydra builds, so I don't have to build the kernel regularly when using that kernel.

**Comment by samueldr** [comment]
Oh, I forgot, I'm still on a side-quest working on *something cool* which means my time spent on Mobile NixOS has been quite low :/.

**Comment by samueldr** [comment]
Thank you!

**Pull request merged**
